/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex('clients').del()
  await knex('clients').insert([
    {
      id: 1,
      business_name: 'Powlowski Mraz and Effertz',
      contact_name: 'Westbrooke Alders',
      email: 'walders0@wired.com',
      phone: '272-793-5878',
      address: '4652 Schmedeman Junction',
      rate: 49,
      isActive: false,
    },
    {
      id: 2,
      business_name: 'Schoen, Marks and Durgan',
      contact_name: 'Adda Franzman',
      email: 'afranzman1@mlb.com',
      phone: '896-260-7037',
      address: '4 Pawling Road',
      rate: 45,
      isActive: true,
    },
    {
      id: 3,
      business_name: 'MacGyver Walter and Feest',
      contact_name: 'Jeramey Jaouen',
      email: 'jjaouen2@fc2.com',
      phone: '228-224-1384',
      address: '67047 Gulseth Park',
      rate: 84,
      isActive: true,
    },
    {
      id: 4,
      business_name: 'Koepp and Sons',
      contact_name: 'Melita Gerdts',
      email: 'mgerdts3@newyorker.com',
      phone: '874-941-3292',
      address: '77 Fieldstone Pass',
      rate: 57,
      isActive: false,
    },
    {
      id: 5,
      business_name: 'Turner LLC',
      contact_name: 'Shanie Trotton',
      email: 'strotton4@nationalgeographic.com',
      phone: '782-734-8367',
      address: '14 Menomonie Circle',
      rate: 46,
      isActive: true,
    },
    {
      id: 6,
      business_name: 'Paucek Feest and Gusikowski',
      contact_name: 'Denys Brito',
      email: 'dbrito5@nbcnews.com',
      phone: '426-981-0216',
      address: '1 Nevada Avenue',
      rate: 91,
      isActive: true,
    },
    {
      id: 7,
      business_name: 'Reynolds Mueller and Bode',
      contact_name: 'Malchy Hurlestone',
      email: 'mhurlestone6@hao123.com',
      phone: '471-220-9739',
      address: '54841 Milwaukee Circle',
      rate: 59,
      isActive: false,
    },
    {
      id: 8,
      business_name: 'Blanda-Conn',
      contact_name: 'Mariel Bond',
      email: 'mbond7@simplemachines.org',
      phone: '192-604-3340',
      address: '48687 Monica Street',
      rate: 66,
      isActive: true,
    },
    {
      id: 9,
      business_name: 'Ebert LLC',
      contact_name: 'Lexy McInerney',
      email: 'lmcinerney8@wufoo.com',
      phone: '467-898-6668',
      address: '658 Melody Place',
      rate: 87,
      isActive: false,
    },
    {
      id: 10,
      business_name: 'Schoen-White',
      contact_name: 'Katee Roussel',
      email: 'kroussel9@shareasale.com',
      phone: '812-564-2524',
      address: '7102 Kenwood Avenue',
      rate: 39,
      isActive: false,
    },
  ])
}
